[[pages]]
path = "home.py"
name = "Home Page"
icon = "ğŸ "
is_section = false

[[pages]]
path = "pages/dashboard.py"
name = "Dashboard"
icon = ":bar_chart:"
is_section = false

[[pages]]
path = "pages/dummy.py"
name = ""
icon = ""
is_section = true